name: book_store_admin
description: "Admin client for the z17 Book Store app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.3.1
  easy_dynamic_theme: ^2.2.0
  envied: ^0.5.4+1
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.4
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.5
  go_router: 13.2.2
  hugeicons: ^0.0.10
  image_picker: ^1.2.0
  image_picker_for_web: ^3.1.0
  infinite_scroll_pagination: 4.0.0
  loader_overlay: 4.0.0
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  parse_server_sdk_flutter: ^9.0.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  syncfusion_flutter_datagrid: ^29.1.38

dependency_overrides:
  http: ^1.3.0
  idb_shim: 2.6.1+7
  intl: ^0.19.0
  uuid: ^4.4.0
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.5
  envied_generator: ^0.5.4+1
  flutter_launcher_icons: null
  flutter_lints: ^4.0.0

flutter_assets:
  assets_path: assets/
  output_path: lib/presentation/app/constants/
  filename: assets.dart

flutter:
  uses-material-design: true

  assets:
    - assets/icon_app/
    - assets/images/
    - assets/svgs/
    - assets/svgs/flags/
    - assets/
